Ext.define('AOC.model.SalesOrderModel',{
    extend: 'Ext.data.Model',
	idProperty:null,
	fields: [
	         // set up the fields mapping into the xml doc
	         {name: 'Division', mapping:'division',type: 'string'},
	 		{name: 'OrderSource', mapping:'orderSource',type: 'string'},
	 		{name: 'SOLDTORBONumber', mapping:'Title',type: 'string'},
	 		{name: 'SOLDTORBONumber', mapping:'soldTORBONumber',type: 'string'},
	 		{name: 'OracleBilltoSiteNumber', mapping:'oracleBilltoSiteNumber',type: 'string'},
	 		{name: 'OracleShiptoSiteNumber', mapping:'oracleShiptoSiteNumber',type: 'string'},
	 		{name: 'Shippingmethod', mapping:'shippingMethod',type: 'string'},
	 		{name: 'CustomerPONumber', mapping:'customerPONumber',type: 'string'},
	 		{name: 'RetailerpoCustomerjob', mapping:'retailerPO_CustomerJob',type: 'string'},
	 		{name: 'OracleItemNumber', mapping:'oracleItemNumber',type: 'string'},
	 		{name: 'CustomerItemNumber', mapping:'customerItemNumber',type: 'string'},
	 		{name: 'ItemDescription', mapping:'itemDescription',type: 'string'},
	 		{name: 'OrderdedQty', mapping:'orderdedQty',type: 'string'},
	 		{name: 'DateOrdered', mapping:'dateOrdered',type: 'string'},
	 		{name: 'Requestdate', mapping:'ustomerRequestDate',type: 'string'},
	 		{name: 'promisedate', mapping:'promiseDate',type: 'string'},
	 		{name: 'Freightterm', mapping:'freightTerms',type: 'string'},
	 		{name: 'CSR', mapping:'csr',type: 'string'},
	 		{name: 'packinginstruction', mapping:'packingInstruction',type: 'string'},
	 		{name: 'Shippinginstruction', mapping:'shippingInstructions',type: 'string'},
	 		{name: 'Invoicelineinstruction', mapping:'invoicelineInstruction',type: 'string'},
	 		{name: 'divisionforInterfaceERPORG', mapping:'divisionforInterfaceERPORG',type: 'string'},
	 		{name: 'Billtocontact', mapping:'billToContact',type: 'string'},
	 		{name: 'Billtotel', mapping:'billToTEL',type: 'string'},
	 		{name: 'BilltoFAX', mapping:'billToFAX',type: 'string'},
	 		{name: 'BilltoEMAIL', mapping:'billToEMAIL',type: 'string'},
	 		{name: 'Shiptocontact', mapping:'shipTOContact',type: 'string'},
	 		{name: 'Shiptotel', mapping:'shipTOTEL',type: 'string'},
	 		{name: 'ShiptoFAX', mapping:'shipTOFAX',type: 'string'},
	 		{name: 'ShiptoEMAIL', mapping:'shipTOEMAIL',type: 'string'},
	 		{name: 'Artworkhold', mapping:'artworkhold',type: 'string'},
	 		{name: 'ArtworkforReference', mapping:'artworkworkattachment',type: 'string'},
	 		{name: 'VariabledataBreakdown', mapping:'variableDataBreakdown',type: 'string'},
	 		{name: 'ManuNote', mapping:'manufacturingnotes',type: 'string'},
	 		{name: 'Ordertype', mapping:'ordertype',type: 'string'},
	 		{name: 'Orderby', mapping:'orderby',type: 'string'},
	 		{name: 'Shippingonlynote', mapping:'shippingonlynotes',type: 'string'},
	 		{name: 'Bankcharge', mapping:'bankCharge',type: 'string'},
	 		{name: 'Freightcharge', mapping:'freightCharge',type: 'string'},
	 		{name: 'Shippinghold', mapping:'shippinghold',type: 'string'},
	 		{name: 'Productionhold', mapping:'productionhold',type: 'string'},
	 		{name: 'Splitshipsetby', mapping:'splitshipset',type: 'string'},
	 		{name: 'Agreement', mapping:'agreement',type: 'string'},
	 		{name: 'ModelserialNumber', mapping:'modelSerialNumber',type: 'string'},
	 		{name: 'WaiveMOQ', mapping:'waiveMOQ',type: 'string'},
	 		{name: 'APOtype', mapping:'apoType',type: 'string'}
	     ]
});