var addImage='avery/resources/images/add.png',
menuIcon='avery/resources/images/menuList.png',
editIcon='avery/resources/images/edit.png',
BackIcon='avery/resources/images/backButton.png',
commentIcon='avery/resources/images/comment.png',
mailIcon='avery/resources/images/mail.png',
browseIcon='avery/resources/images/browse.png',
backText='Back',
advSearchIcon='avery/resources/images/search.png',advSearchText='Adv. Search',
centerStyleDiv='<div align="center"><b><font color=#006FDD>',
clearSearchIcon='avery/resources/images/invalid_field.png',
errorIcon='avery/resources/images/invalid_field.jpg',
tickIcon='avery/resources/images/tick.png',
errorStatusIcon='avery/resources/images/error.png',
cancelIcon='avery/resources/images/cancel.png',
cancelOrderText='<b>Are you sure you want to cancel the Order? If yes, please enter the reason for futher reference:</b> ',
advancedSearchWindowTitle='Advanced Search',
createSalesOrderBtnText='<b>Create Sales Order</b>',
viewSalesOrderBtnText='<b>View Sales Order</b>',
cancelText='<b>cancel</b>',
ResetText='Reset',
cancelSalesOrderText='<b>Cancel Sales Order</b>',
salesOrdersumbitText='<b>Submit Sales Order</b>',
dateFormat='Y-m-d',
bulkUpdateButtonText='<b>Bulk Update</b>',
attacheImageSrc='avery/resources/images/attachmentImage.png',
deleteImageSrc='avery/resources/images/delete.png',
warningImageSrc='avery/resources/images/warning.png',
successImageSrc='avery/resources/images/success.jpg',
cellColor='background-color:#FFC7B0;',
editPartnerMsg='<b>This partner is Active. To edit a partner , it must be InActive.</b>',
//Status Code
orderReceivedStatus='1',
orderError='2',
orderPreProcessedStatus='3',
waitingForCSRStatus='4',
salesOrderCreatedStatus='5',
submitToOracleStatus='6',

cancelStatus='8',
	
fiberLevel='FIBRE',
mandatoryValidationCellColor='background-color:yellow',
undoChangesText='Undo',
averyItemNotFoundText='NOT FOUND'


;

