var addImage='avery/resources/images/add.png',
menuIcon='avery/resources/images/menuList.png',
editIcon='avery/resources/images/edit.png',
BackIcon='avery/resources/images/backButton.png',
CommentIcon='avery/resources/images/comment.png',
MailIcon='avery/resources/images/mail.png',
BrowseIcon='avery/resources/images/browse.png',
backText='Back',
advSearchIcon='avery/resources/images/search.png',advSearchText='Adv. Search',
centerStyleDiv='<div align="center"><b><font color=#006FDD>',
clearSearchIcon='avery/resources/images/invalid_field.jpg',
errorIcon='avery/resources/images/invalid_field.jpg',
cancelOrderText='<b>Are you sure you want to cancel the Order? If yes, please enter the reason for futher reference:</b> ',
advancedSearchWindowTitle='Advanced Search',
cancelStatus='8'
createSalesOrderBtnText='<b>Create Sales Order</b>',
viewSalesOrderBtnText='<b>View Sales Order</b>',
cancelText='<b>cancel</b>',
cancelSalesOrderText='<b>Cancel Sales Order</b>',
salesOrdersumbitText='<b>Submit to System</b>',
submitToOracleStatus='6',
dateFormat='Y-m-d',
bulkUpdateButtonText='<b>Bulk Update</b>'
;

